default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: claquete_business_development
  password: postgres
  port: 5433
  host: localhost

test:
  <<: *default
  database: claquete_business_test
  password: postgres
  port: 5433
  host: localhost
 
# production:
#   <<: *default
#   database: claquete_business_production
#   username: <%= ENV['CLAQUETE_BUSINESS_DATABASE_USER'] %>
#   password: <%= ENV['CLAQUETE_BUSINESS_DATABASE_PASSWORD'] %>
#   host: <%= ENV['CLAQUETE_BUSINESS_DATABASE_URL'] %>
production:
  <<: *default
  database: claquete_business_production
  username: claquete_business
  password: eDveTZmKkarm6cV
  host: 35.193.11.228